// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewQuote struct {
	Text   string `json:"text"`
	Author string `json:"author"`
}

type Query struct {
}

type Quote struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Author string `json:"author"`
}

type UpdateQuote struct {
	Text   string `json:"text"`
	Author string `json:"author"`
}
