package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"graphql/graph/model"
)

// CreateQuote is the resolver for the createQuote field.
func (r *mutationResolver) CreateQuote(ctx context.Context, input model.NewQuote) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: CreateQuote - createQuote"))
}

// UpdateQuote is the resolver for the updateQuote field.
func (r *mutationResolver) UpdateQuote(ctx context.Context, id string, input model.UpdateQuote) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: UpdateQuote - updateQuote"))
}

// DeleteQuote is the resolver for the deleteQuote field.
func (r *mutationResolver) DeleteQuote(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteQuote - deleteQuote"))
}

// Quotes is the resolver for the quotes field.
func (r *queryResolver) Quotes(ctx context.Context) ([]*model.Quote, error) {
	panic(fmt.Errorf("not implemented: Quotes - quotes"))
}

// Quote is the resolver for the quote field.
func (r *queryResolver) Quote(ctx context.Context, id string) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: Quote - quote"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}
*/
